#!/usr/bin/env bash

perms=(
  [py]=+x
  [sh]=+x
)
export perms

DATE="$(date)"
export DATE
export AUTHOR="nyped"
export CPP_HEADER="#include <iostream>"
export C_HEADER="#include <stdio.h>"
export C_MODELINE="/* vim: set ts=4 sts=4 sw=4 et : */"
export MAKE_CC="gcc"
export MAKE_CFLAGS="-Wall -g -Werror -pedantic"
export MD_MODELINE="
<!-- ltex: language=fr -->
<!-- ltex: enabled=true -->

<!-- vim:set ts=4 sts=4 sw=4 tw=80 et: -->"
export PY_MODELINE="# vim: set ts=4 sts=4 sw=4 noet :"
export SH_MODELINE="# vim: set ts=2 sts=2 sw=2 et :"

# vim:set ts=8 sts=2 sw=2 et syn=sh:
