#!/usr/bin/env zsh

# Create the alias if a binary is in the path:
# altif foo bar
# altif foo foo=bar200
function altif() {
  type "$1" &>/dev/null || return
  if [[ -n $3 ]]; then
    alias "$2=$3"
  else
    alias "$2=$1"
  fi
}

# general
alias _='sudo '
alias grep='grep --color=always'
alias ip='ip -c'
alias diff='diff --color=always'
altif curl lorem 'curl -s http://metaphorpsum.com/sentences/3'
altif firefox ff
altif open o
altif pacman p
altif pacman prmo 'pacman -Qqtd | sudo pacman -Rns -'
altif yay y

# translation stuff
altif trans t
altif trans tb 'trans -brief'

# vim
altif vi    v 'vi -p'
altif vim   v 'vim -p'
altif nvim  v 'nvim -p'
altif nvim  vr 'v -R'

# TODO: add scripts to PATH
altif "$HOME/bin/color" c

# bat
altif bat    b
altif batcat b
altif b      bp 'b -p'

# ip
altif curl myip 'curl ifconfig.me'

# clipboard
if [[ -n $WAYLAND_DISPLAY ]]; then
  altif wl-copy  pbcopy
  altif wl-paste pbpaste
else
  altif xclip pbcopy 'xclip -selection clipboard'
  altif xclip pbpaste 'xclip -selection clipboard -o'
fi
altif pbcopy pbc
altif pbcopy pbk 'pbcopy < /dev/null'
altif pbpaste pbp
altif nc      pbs 'nc termbin.com 9999'

# history
alias h='history'
alias hh='history 1'
alias hs='history 1 | grep'

# make
altif make m
altif make mc 'make clean'
altif make mb 'make -B'
altif make mr 'make clear'
altif make mt 'make test'

# quick cd
alias -- -='cd -'
alias 0='cd -10'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias dl='cd ~/Downloads'
alias tmp='cd /tmp'

# ripgrep
altif grep rg 'grep -r'
altif rg   rg 'rg'
alias rg2='rg -C2'
alias rg3='rg -C3'
alias rg4='rg -C4'
alias rg5='rg -C5'
alias rgi2='rg -iC3'
alias rgi3='rg -iC3'
alias rgi4='rg -iC4'
alias rgi5='rg -iC5'
alias rgi='rg -i'

# git
alias g='git'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit -v'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gl='git log'
alias gl='git pull'
alias gm='git merge'
alias gp='git push'
alias gr='git rebase'
alias gs='git switch'
alias gsp='git stash push'
alias gss='git stash show'
alias gst='git status'
alias gw='git worktree'
alias gwl='git worktree list'

# ls
alias l='ls -lah'
alias la='ls -A'
alias ll='ls -lh'
altif exa ls
altif eza ls

# Clean up
unfunction altif

# vim: set ts=2 sts=2 sw=2 ft=sh et :
