#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

monitors=($(bspc query -M --names | sort))
xrandr --output "${monitors[0]}" --auto --output "${monitors[1]:-HDMI-1}" --auto --right-of "${monitors[0]}"

if [ "$(< ~/.t)" = day ]
	then ~/dotfiles/scripts/color.sh day
	else ~/dotfiles/scripts/color.sh night
fi

xsetroot -cursor_name left_ptr

bspc config focused_border_color \#9ba2b0
bspc config normal_border_color \#9ba2b0
bspc config active_border_color \#9ba2b0
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus    true
bspc config pointer_motion_interval 7
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config split_ratio          0.5
bspc config window_gap          12
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-1 -d 11 12 13 14 15 16 17 18 19 20
bspc config border_width         1
bspc config top_padding 32
bspc config external_rules_command /home/lenny/dotfiles/bspwm/external_rules.sh

~/dotfiles/polybar/launch.sh
~/dotfiles/bspwm/urgent_win.sh &
disown
