#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if cat ~/.config/termite/config | grep day > /dev/null 2>&1
	then ~/dotfiles/scripts/color.sh day
	else ~/dotfiles/scripts/color.sh night
fi

xsetroot -cursor_name left_ptr

bspc config focus_follows_pointer true
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1' follow=off
bspc rule -a discord desktop='^5' follow=off
bspc rule -a Termite desktop='^3' follow=off
bspc rule -a Zathura desktop='^4' follow=off
bspc rule -a libreoffice-startcenter desktop='^8' follow=off

~/dotfiles/polybar/launch.sh
