#!/usr/bin/env bash
# scripts/weather_meta
# Sun Dec 12 12:49:44 AM CET 2021
# lennypeers

fallback="ﭽ|unknown|-"
in=$(curl -s 'wttr.in/?format=%c|%C|%t' 2>/dev/null)

[[ -z $in ]] && {
  in="$fallback"
}

IFS='|' read -r logo condition temperature <<< $in
eww update \
  weather_logo="$logo" \
  weather_condition="$condition" \
  weather_temperature="${temperature%°C}"

echo

# vim:set ts=8 sts=2 sw=2 et:
