#!/usr/bin/env bash
# scripts/weather_meta
# Sun Dec 12 12:49:44 AM CET 2021
# lennypeers

fallback="ﭽ|unknown|-"
in=$(curl -s 'wttr.in/grenoble?format=%c|%C|%t' 2>/dev/null)

case "$in" in
  *HTML* | "" | *Unknown*)
    in="$fallback"
  ;;
esac

IFS='|' read -r logo condition temperature <<< $in
eww update \
  weather_logo="$logo" \
  weather_condition="$condition" \
  weather_temperature="${temperature%°C}"

echo

# vim:set ts=8 sts=2 sw=2 et:
