#!/usr/bin/env zsh

[[ $1 = -h || $1 == --help ]] && exec cat >&2 <<EOF
usage: ${0%%*/} [-h | --help | THEME]
Switch themes: update configuration file with symlinks and load them.
THEME can be day (or d), or night (or night)
EOF

if [[ $1 = day || $1 = d ]]; then
	THEME=day
elif [[ $1 = night || $1 = n ]]; then
	THEME=night
else
	THEME=$(< ~/.t)
	[[ $THEME = day ]] && exec $0 n || exec $0 d
fi

echo $THEME > ~/.t

ln -sf ~/dotfiles/${THEME}-theme/bat.conf ~/.config/bat/config
ln -sf ~/dotfiles/${THEME}-theme/dunstrc ~/.config/dunst/dunstrc
ln -sf ~/dotfiles/${THEME}-theme/rofi.rasi ~/.config/rofi/config.rasi
ln -sf ~/dotfiles/${THEME}-theme/zathurarc ~/.config/zathura/zathurarc
ln -sf ~/dotfiles/kitty/kitty-${THEME}-scheme.conf ~/.config/kitty/color-scheme.conf
ln -sf ~/dotfiles/wallpaper/${THEME}.png ~/Pictures/wallpaper.png

{
	hsetroot -cover ~/Pictures/wallpaper.png
	killall dunst
	kill -SIGUSR1 $(pidof nvim)
	kill -SIGUSR1 $(pidof kitty)
	eww update theme=$THEME &
} &>/dev/null

polybar-msg action "#light_laptop.hook.2"
polybar-msg action "#light_mon.hook.2"

# vim: set ts=4 sts=4 sw=4 noet :
