#!/bin/bash
#
# change fan speed with rofi dmenu

shopt -s extglob

ret=$(echo -e "Toggle\nSlow\nMedium\nFast" | rofi -dmenu -i -p "Fan menu:" -l 2)

case $ret in
  [Tt]oggle)
    if [ $(mmf toggle) = 0 ]
      then mes="Fan in auto-control"
      else mes="Fan in manual control"
    fi
    ;;

  +([[:digit:]]))
    if [ -1 -le $ret -a $ret -le 6500 ]; then
      mmf $ret
      mes="Set to $ret rpm"
    else
      mes="Incorrect fan speed"
    fi
    ;;

  [[:digit:]]k)
    ret=${ret/k/000} mes="Set to $ret rpm"
    mmf $ret
    ;;

  [Mn]edium)
    mmf 4000
    mes="Set to 4000 rpm"
    ;;

  [Ff]ast)
    mmf 6000
    mes="Set to 6000 rpm"
    ;;

  [Ss]low)
    mmf 2000
    mes="Set to 2000 rpm"
    ;;

  "")
    ;;

  *)
    mes="Failed to parse command"
    ;;
esac

[ -z "$mes" ] || notify-send Fan "$mes" -a notif

# vim: set ts=2 sts=2 sw=2 et :
