#!/usr/bin/env bash
# hwmon
# Sat Apr  2 05:06:00 PM CEST 2022

dell_fan=/sys/bus/platform/drivers/dell_smm_hwmon/dell_smm_hwmon/hwmon/hwmon5/fan1_input
dell_cpu=/sys/bus/platform/drivers/dell_smm_hwmon/dell_smm_hwmon/hwmon/hwmon5/temp2_input

apple_fan=/sys/devices/platform/applesmc.768/fan1_input
apple_cpu=/sys/devices/platform/applesmc.768/temp13_input

if [[ -f $apple_cpu ]]; then
  cpu_temp=$apple_cpu
else
  cpu_temp=$dell_cpu
fi

if [[ -f $apple_fan ]]; then
  fan_speed=$apple_fan
else
  fan_speed=$dell_fan
fi

while :
do
  temp=$(cat $cpu_temp)
  speed=$(cat $fan_speed)
  out="${temp%%???}°%{T3}c%{T}"
  [[ $speed > 0 ]] && \
    out+="    $speed %{T3}rpm"
  echo "$out"
  sleep 3
done

# vim:set ts=8 sts=2 sw=2 et:
