#!/usr/bin/env bash
# kb
# Mon May 17 03:56:00 PM CEST 2021
# lennypeers

usage() {
  cat << EOF
usage: kb [-m | --mac | -e | --external | -h | --help]
EOF
}

case "$1" in
  -m | --mac)
    setxkbmap -option
    setxkbmap \
      -layout us \
      -option ctrl:swap_lwin_lctl \
      -option ctrl:swap_rwin_rctl \
      -option caps:none \
      -option compose:ralt \
      -option altwin:menu_win
    xmodmap \
      -e "clear Lock" \
      -e "keycode 0x42 = BackSpace BackSpace BackSpace"
  ;;

  -e | --external) # external kb
    setxkbmap -option -layout us
    xmodmap \
      -e "clear Lock" \
      -e "keycode 0x42 = BackSpace BackSpace BackSpace" \
      -e "remove Mod1 = Alt_L" \
      -e "remove Mod4 = Super_L" \
      -e "remove Control = Control_L" \
      -e "keysym Alt_L = Control_L" \
      -e "keysym Super_L = Alt_L Meta_L" \
      -e "keysym Control_L = Super_L" \
      -e "keysym Menu = Multi_key" \
      -e "add Control = Control_L Control_R" \
      -e "add Mod1 = Alt_L Meta_L" \
      -e "add Mod4 = Super_L"
  ;;

  -h | --help)
    usage
    exit 0
  ;;

  *)
    usage
    exit 255
  ;;
esac

# vim:set ts=8 sts=2 sw=2 et:
