#!/usr/bin/env bash

ret=$(
cat <<EOF | rofi -dmenu -i -p Do: -lines 4 -columns 4
Lock
Reboot
Shutdown
Suspend
Screen
Record
Theme
Music
Dock
Multihead
Monohead
Editor
EOF
)
case $ret in
	Lock)
		~/dotfiles/scripts/lock
		;;

	Reboot)
		shutdown -r now
		;;

	Shutdown)
		shutdown now
		;;

	Record)
		~/dotfiles/scripts/screencast -d &
		;;

	Theme)
		~/dotfiles/scripts/color
		;;

	Screen | Screenshoot)
		~/dotfiles/scripts/screenshot -s
		;;

	Suspend)
		systemctl suspend
		;;

	Music)
		spotify  --no-zygote --disable-gpu --disable-software-rasterizer &
		disown
		;;

	Dock)
		~/dotfiles/scripts/monitors -d
		~/dotfiles/scripts/keyboard -e
		;;

	Multihead)
		~/dotfiles/scripts/monitors -m
		~/dotfiles/scripts/keyboard -e
		;;

	Monohead)
		~/dotfiles/scripts/monitors -l
		~/dotfiles/scripts/keyboard -m
		;;

	Editor)
		alacritty -e nvim &
		disown
		;;

	"")
		: # pass
		;;

	*)
		notify-send Error "Couldn't parse the command"
		;;
esac
