#!/usr/bin/env bash

usage() {
    cat << _HELPTXT
Usage: ${0##*/} [--help | -h | --dock | -d | --multi | -m | --laptop | -l]
-d, --dock     output on external monitor only
-l, --laptop   output on laptop screen only
-m, --multi    output on external monitor and laptop screen
-h, --help     show this message
_HELPTXT
}

# bruh different names...
if [[ $HOSTNAME == iron ]]; then
  external=HDMI-A-0
  external_scale=1.25x1.25
  laptop1=eDP
  laptop2=LVDS
else
  external=HDMI1
  external_scale=1x1
  laptop1=eDP1
  laptop2=LVDS1
fi

case "$1" in
  -h | --help)
    usage
    exit 0
  ;;

  -d | --dock) # laptop monitor off (dock)
    xrandr \
      --output  $laptop1 --off \
      --output $laptop2 --off \
      --output $external --auto \
      --scale $external_scale \
      &>/dev/null
  ;;

  -m | --multi) # multi head
    xrandr \
      --output $laptop2 --auto --primary --left-of $external \
      --output  $laptop1 --auto --primary --left-of $external \
      --output $external --auto --scale $external_scale \
      &>/dev/null
  ;;

  -l | --laptop) # laptop only
    # moving windows
    for node in $(bspc query -N -m $external); {
      a=$(bspc query -D -n $node --names) a=$((a-10))
      bspc node $node -d $a
    }

    xrandr \
      --output $external --off \
      --output $laptop2 --auto \
      --output  $laptop1 --auto \
      &>/dev/null
  ;;

  *)
    usage
    exit 255
  ;;
esac

bspc wm -r

# vim:set ts=8 sts=2 sw=2 et:
