#!/usr/bin/env bash

usage() {
    cat << _HELPTXT
Usage: ${0##*/} [--help | -h | --dock | -d | --multi | -m | --laptop | -l]
-d, --dock     output on external monitor only
-l, --laptop   output on laptop screen only
-m, --multi    output on external monitor and laptop screen
-h, --help     show this message
_HELPTXT
}

case "$1" in
  -h | --help)
    usage
    exit 0
  ;;

  -d | --dock) # laptop monitor off (dock)
    xrandr \
      --output  eDP-1 --off \
      --output LVDS-1 --off \
      --output HDMI-1 --auto \
      &>/dev/null
  ;;

  -m | --multi) # multi head
    xrandr \
      --output LVDS-1 --auto --primary --left-of HDMI-1 \
      --output  eDP-1 --auto --primary --left-of HDMI-1 \
      --output HDMI-1 --auto \
      &>/dev/null
  ;;

  -l | --laptop) # laptop only
    # moving windows
    for node in $(bspc query -N -m HDMI-1); {
      a=$(bspc query -D -n $node --names) a=$((a-10))
      bspc node $node -d $a
    }

    xrandr \
      --output HDMI-1 --off \
      --output LVDS-1 --auto \
      --output  eDP-1 --auto \
      &>/dev/null
  ;;

  *)
    usage
    exit 255
  ;;
esac

bspc wm -r

# vim:set ts=8 sts=2 sw=2 et:
