#!/usr/bin/env bash
# scripts/music_meta
# Sat Dec 11 02:23:27 PM CET 2021

key='{{status}}|{{mpris:artUrl}}|{{title}}'
PAUSE= PLAY=契 PLAYING=ﱘ
destination=/tmp/spotify_cover.png

if [[ $1 != init ]]; then
  arg="--follow"
fi

playerctl $arg metadata --format $key | {
  while IFS='|' read -r status url title; do
    pidof eww &>/dev/null || continue

    if [[ $status == Playing ]]; then
      icon=$PAUSE
    else
      icon=$PLAY
    fi

    if [[ -z $url ]]; then
      cover=/home/lenny/.config/eww/assets/cover.png
    else
      curl -sL "$url" -o $destination &>/dev/null
      cover=$destination
    fi

    eww update \
      current_song="${title:-Not playing}" \
      player_icon="$icon" \
      cover_path="$cover" &>/dev/null
  done
}

# vim:set ts=8 sts=2 sw=2 et:
