#!/usr/bin/env bash
# network_watcher
# Sun Dec 12 11:53:19 PM CET 2021
# lennypeers

splash() {
  echo "睊"
  in="$(nmcli con show --active)"
  grep -q wifi <<< $in && echo "直"
  grep -q ethernet <<< $in && echo ""
}

splash

nmcli monitor | {
  while read -r; do
    case "$REPLY" in
      "Connectivity is now 'none'" | *connected)
        splash
      ;;

      *)
      ;;
    esac
  done
}

# vim:set ts=8 sts=2 sw=2 et:
