#!/usr/bin/env bash
# net
# Fri Dec 17 06:27:52 PM CET 2021
# lennypeers

names=$(nmcli -t -f name connection show --active)
payload=None

[[ -n $names ]] && \
  payload="<b>${names//$'\n'/$'</b> and <b>'}</b>"

notify-send Network "Connected to: $payload" \
  -h string:x-canonical-private-synchronous:anything


# vim:set ts=8 sts=2 sw=2 et:
