#!/usr/bin/env bash
#
# quick scrots
# https://thurlow.io/linux/2017/11/10/replicating-macos-screenshot-utility-on-linux.html

function usage() {
cat <<EOF >&2
Usage: ${1##*/} <cmd>
Available commands:
-w  --windows       capture the focused window
-a  --all           capture the whole screen
-s  --select        capture the selected part (default)
-c  --clipboard     save to the clipboard
-S  --shadows       add macos like shadows
-n  --dry-run       perform a trial run with no changes
-h  --help          show help
EOF
}

name="${HOME}/Screenshots/$(date +%F-%Hh%Mm%Ss-screenshot)"
flags="-border -quality 0 "
payload="saved as ${name##*/}.png"

while [[ -n "$1" ]]; do
  case "$1" in
    -w | --windows)
      flags+="-windows $(bspc query -N -n .local.focused)"
      ;;

    -a | --all)
      flags+="-windows root"
      ;;

    -s | --select)
      :
      ;;

    -S | --shadows)
      shad=1
      ;;

    -h | --help)
      usage
      exit 0
      ;;

    -n | --dry-run)
      dry=1
      ;;

    -c | --clipboard)
      clip=1 payload="copied to the clipboard"
      ;;

    *)
      usage $0 && exit 1
    ;;
  esac

  shift
done

[[ -n $dry ]] && set -nv

# dumping the pixels from ram
import $flags "${name}.xwd"

# shadows
if [[ "${shad}" == 1 ]]; then
  convert                                             \
    "${name}.xwd"                                     \
    \( +clone -background black -shadow 60x10+0+10 \) \
    +swap                                             \
    -background transparent                           \
    -layers merge                                     \
    +repage                                           \
    -quality 0                                        \
    "${name}.png"
  else
    convert "${name}.xwd" "${name}.png"
fi

rm "${name}.xwd"

notify-send                  \
  Screenshot                 \
  "$payload"                 \
  --icon "${name}.png"

[[ -n $clip ]] && {
  xclip -selection clipboard -t image/png -i "${name}.png"
  rm "${name}.png"
}

# vim: set ts=2 sts=2 sw=2 et :
