#!/usr/bin/env bash

update() {
  pactl set-sink-volume @DEFAULT_SINK@ ${1:-+5}%
}

info() {
  cat << EOF
usage: ${0##*/} <cmd>
Available commands:
-h, --help       show help
-t, --toggle     toggle mute
-i, --inc N      increase the volume of N percentages
-d, --dec N      decrease the volume of N percentages
-n, --notify     send a notification

output: percentage muted
- percentage an integer
- muted is [yes | no]
EOF
}

while [[ $# != 0 ]]; do
  case "$1" in
    -t | --toggle)
      opp=toggle
    ;;

    -i | --inc)
      shift
      opp=i val="$1"
    ;;

    -d | --dec)
      shift
      opp=d val="$1"
    ;;

    -h | --help)
      info
      exit 0
    ;;

    -n | --notify)
      NOTIFY=1
    ;;

    *) # fallthrough
      info >&2
      exit 255
    ;;
  esac

  shift
done

case "$opp" in
  toggle)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
  ;;

  i)
    update "+$val"
  ;;

  d)
    update "-$val"
  ;;
esac

is_muted="$(pactl get-sink-mute '@DEFAULT_SINK@' | awk '{print $2}')"
percentage="$(pactl get-sink-volume '@DEFAULT_SINK@' | awk '{gsub("%",""); print $5}')"

echo $percentage $is_muted

[[ $is_muted == yes ]] && tail=" (muted)"

[[ -n $NOTIFY ]] && \
  notify-send "Volume" "at ${percentage}%${tail}" \
    -h string:x-canonical-private-synchronous:anything \
    -a notif \
    -h int:value:$percentage

# vim: set ts=2 sts=2 sw=2 et :
