#!/bin/bash
# this comment is a waste of bits !

update() {
  pactl set-sink-volume @DEFAULT_SINK@ ${1:-+5}%
}

info() {
  cat << EOF
usage: ${0##*/} <cmd>
Available commands:
-h, --help       show help
-t, --toggle     toggle mute
-i, --inc N      increase the volume of N percentages
-d, --dec N      decrease the volume of N percentages

output: percentage muted
- percentage an integer
- muted is [yes | no]
EOF
}

while [[ $# != 0 ]]; do
  case "$1" in
    -t | --toggle)
      opp=toggle
    ;;

    -i | --inc)
      shift
      opp=i val="$1"
    ;;

    -d | --dec)
      shift
      opp=d val="$1"
    ;;

    -h | --help)
      info
      exit 0
    ;;

    *) # fallthrough
      info >&2
      exit 255
    ;;
  esac

  shift
done

case "$opp" in
  toggle)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
  ;;

  i)
    update "+$val"
  ;;

  d)
    update "-$val"
  ;;
esac

is_muted="$(pactl list | awk '/Mute:/{i++}i==1 { print $2; exit }')"
percentage="$(pactl list sinks | grep -m 1 \%\ \/ | cut -d \/ -f 2 | sed -e s/\ //g -e s/\%//)"

echo $percentage $is_muted

# vim: set ts=2 sts=2 sw=2 et :
