#!/usr/bin/env zsh

export XDG_SESSION_TYPE=x11 GDK_BACKEND=x11
picom --config ~/dotfiles/X/picom.conf -b --experimental-backend
systemctl --user import-environment DISPLAY XAUTHORITY
xrdb -merge ~/.Xresources
xset s off
xset s noblank

# setting keyboard layout
if [[ $HOST == iron ]]; then
	~/dotfiles/scripts/keyboard -e
else
	~/dotfiles/scripts/keyboard -m
fi

exec bspwm
