#!/bin/zsh

export XDG_SESSION_TYPE=x11 GDK_BACKEND=x11
picom --config ~/dotfiles/X/picom.conf -b --experimental-backend
systemctl --user import-environment DISPLAY
xrdb -merge ~/.Xresources
xset s off
xset s noblank
~/dotfiles/scripts/keyboard -m
exec bspwm
