HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.zsh_history

setopt autocd extendedglob nomatch interactive_comments
unsetopt beep

# colors
autoload -U colors
colors

# keybinds
bindkey -e
bindkey "^U" backward-kill-line

# Tab completition
autoload -U compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zmodload zsh/complist
compinit
bindkey '^[[Z' reverse-menu-complete

# prompt
source ~/dotfiles/zsh/git.zsh
source ~/dotfiles/zsh/simple.zsh-theme

# arrow search
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end

# delete word
autoload -U select-word-style
select-word-style bash
export WORDCHARS='.-'

# workflow
source ~/dotfiles/zsh/aliasrc
source ~/dotfiles/zsh/functions.sh

## Colors, theme stuff
source ~/.id

# syntax highlight
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# zle stuff
export ZSH_HIGHLIGHT_STYLES[arg0]="none"
export ZSH_HIGHLIGHT_STYLES[path]="fg=cyan,bold"
export ZSH_HIGHLIGHT_STYLES[comment]="fg=blue,bold"
export ZSH_HIGHLIGHT_STYLES[redirection]="fg=yellow,bold"
export ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=blue,bold"
export ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=yellow,bold"

#linux: new terminal tabs keep the same wd
if [ -e /etc/profile.d/vte.sh ]; then
  . /etc/profile.d/vte.sh
fi

#auto startx on TTY1
if [[ $(tty) = /dev/tty1 ]]; then
  exec startx
fi

# vim: set ts=2 sts=2 sw=2 et :
