HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.zsh_history

setopt autocd \
       extendedglob \
       nomatch \
       interactive_comments \
       noflowcontrol \
       auto_pushd \
       complete_in_word \
       hist_ignore_dups \
       hist_ignore_space \
       incappendhistory \
       share_history

unsetopt beep

# colors
autoload -U colors
colors

# keybinds
bindkey -e
bindkey "^U" backward-kill-line

# tab completion
eval "$(dircolors)"
autoload -U compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS} "ma=30;1;42;21"
zstyle ':completion:*' matcher-list \
  '' \
  'm:{a-zA-Z}={A-Za-z}' \
  'm:{A-Z}={a-z} r:|[._-/]=* r:|=* l:|=*' \
  'm:{a-z}={A-Z} r:|[._-/]=* r:|=* l:|=*' \
  'r:|[._-/]=* r:|=* l:|=*'
zmodload zsh/complist
compinit
bindkey '^[[Z' reverse-menu-complete

# arrow search
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end

# delete word
autoload -U select-word-style
select-word-style bash
export WORDCHARS='.-'

# workflow
source ~/dotfiles/zsh/aliasrc
source ~/dotfiles/zsh/functions.sh

# prompt
source ~/dotfiles/zsh/git.zsh
source ~/dotfiles/zsh/simple.zsh-theme

# title update when resize
trap precmd WINCH

# Colors, theme stuff
source ~/.id

# man and pager stuff
export LESS=-r\ --mouse\ --wheel-lines=2
export LESS_TERMCAP_mb=$(tput bold; tput setaf 41) green
export LESS_TERMCAP_md=$(tput bold; tput setaf 6)
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 231; tput setab 241)
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 9)
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)
export TERM=xterm-256color
export EDITOR=nvim
export MANPAGER='nvim -u NORC +"set ft=man noshowcmd noruler noshowmode laststatus=0 scrolloff=500" +Man! +"norm M"'

# qt dark theme
export QT_QPA_PLATFORMTHEME=qt5ct

# firefox
export LIBVA_DRIVER_NAME=i965
export MOZ_X11_EGL=1
export MOZ_USE_XINPUT2=1

# maple
export _JAVA_AWT_WM_NONREPARENTING=1

# cursors
export XCURSOR_PATH=~/.local/share/icons

# syntax highlight
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# zle stuff
export ZSH_HIGHLIGHT_STYLES[arg0]="none"
export ZSH_HIGHLIGHT_STYLES[path]="fg=cyan,bold"
export ZSH_HIGHLIGHT_STYLES[comment]="fg=blue,bold"
export ZSH_HIGHLIGHT_STYLES[redirection]="fg=yellow,bold"
export ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=blue,bold"
export ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=yellow,bold"

# new terminal tabs keep the same wd
if [[ -e /etc/profile.d/vte.sh ]]; then
  . /etc/profile.d/vte.sh
fi

# auto startx on TTY1
if [[ $(tty) = /dev/tty1 ]]; then
  exec startx
fi

# vim: set ts=2 sts=2 sw=2 et :
