return {
  { -- https://github.com/nvim-treesitter/nvim-treesitter
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPre", "BufNewFile" },
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = {
          "bash", -- parsers {{{
          "bibtex",
          "c",
          "cmake",
          "cpp",
          "css",
          "cuda",
          "diff",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "go",
          "groovy",
          "html",
          "ini",
          "java",
          "javascript",
          "json",
          "lua",
          "luadoc",
          "make",
          "markdown",
          "markdown_inline",
          "nix",
          "ocaml",
          "python",
          "r",
          "regex",
          "rust",
          "toml",
          "typescript",
          "typst",
          "vim",
          "vimdoc",
          "yaml",
          -- }}}
        },
        sync_install = false,
        ignore_install = { "" },
        highlight = {
          enable = true,
          disable = {},
          additional_vim_regex_highlighting = false,
        },
      })
    end,
  },
}
