return {
  { -- https://github.com/ziontee113/syntax-tree-surfer
    "ziontee113/syntax-tree-surfer",
    dependencies = "nvim-treesitter/nvim-treesitter",
    keys = {
      { -- Visual Selection from Normal Mode
        "vx",
        vim.cmd.STSSelectMasterNode,
        noremap = true,
        silent = true,
        desc = "TSsurf select master",
      },
      {
        "vn",
        vim.cmd.STSSelectCurrentNode,
        noremap = true,
        silent = true,
        desc = "TSsurf select current",
      },
      { -- Select Nodes in Visual Mode
        "J",
        vim.cmd.STSSelectNextSiblingNode,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf select next sibling",
      },
      {
        "K",
        vim.cmd.STSSelectPrevSiblingNode,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf select Prev sibling",
      },
      {
        "H",
        vim.cmd.STSSelectParentNode,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf select parent",
      },
      {
        "L",
        vim.cmd.STSSelectChildNode,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf select child",
      },
      { -- Swapping Nodes in Visual Mode
        "<A-j>",
        vim.cmd.STSSwapNextVisual,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf swap next visual",
      },
      {
        "<A-k>",
        vim.cmd.STSSwapPrevVisual,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf swap prev visual",
      },
      { -- Holds a node, or swaps the held node
        "<Leader>gs",
        vim.cmd.STSSwapOrHold,
        mode = "n",
        noremap = true,
        silent = true,
        desc = "TSsurf hold and swap (go swap)",
      },
      {
        "<Leader>gs",
        vim.cmd.STSSwapOrHoldVisual,
        mode = "x",
        noremap = true,
        silent = true,
        desc = "TSsurf hold and swap visual (go swap)",
      },
    },
    config = true,
  },
}
